# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20170614_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='aluno',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Aluno'),
            preserve_default=False,
        ),
    ]
