# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20170614_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(max_length=1000, verbose_name='Descrição da ocorrência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
    ]
